# Generated by Django 4.2.5 on 2023-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(max_length=256)),
                ('fecha_consulta', models.DateField(null=True)),
                ('identificacion', models.CharField(max_length=32)),
                ('codigo_cups', models.IntegerField(max_length=5000)),
                ('finalidad_consulta', models.TextField()),
                ('causa_externa', models.IntegerField(max_length=5000)),
                ('codigo_diagnostico_ppal', models.IntegerField(max_length=5000)),
                ('codigo_diag_opc', models.IntegerField(max_length=5000)),
                ('valor_de_consulta', models.IntegerField(max_length=5000)),
                ('valor_total', models.IntegerField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=256)),
                ('genero', models.CharField(max_length=256)),
                ('identificacion', models.CharField(max_length=32)),
                ('antecedentes', models.TextField(max_length=500)),
                ('tipo_id', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('identidicacion', models.CharField(max_length=32)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('especialidad', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=256)),
                ('genero', models.CharField(max_length=256)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('identificacion', models.CharField(max_length=32)),
                ('antecedentes', models.TextField()),
                ('tipo_id', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
